#ifndef LAMP_GLOBALS_H
#define LAMP_GLOBALS_H

#define LAMP_SHADE_PIN 12
#define LAMP_BASE_PIN 14
#define LAMP_DEFAULT_NUMBER_PIXELS 40
#define LAMP_DEFAULT_NAME "standard"
#define LAMP_DEFAULT_HOME_MODE false
#define LAMP_DEFAULT_BRIGHTNESS 100
#define LAMP_TIME_BETWEEN_ACKNOWLEDGEMENT_MS 60000

#endif