# workflows adapted from the WLED project using PlatformIO
name: LampOS Build

# Only included into other workflows
on:
  workflow_call:

jobs:

  build:
    name: Build Environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.12'
          cache: 'pip'
    - name: Install PlatformIO
      run: pip install -r requirements.txt
    - name: Add Secrets
      working-directory: ./software/lamp-os
      run:
        run: |
          cp "src/secrets_sample.hpp" "src/secrets.hpp"  
    - name: Build firmware
      working-directory: ./software/lamp-os
      run: pio run --environment upesy_wroom
    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build_output/release/*.bin
          build_output/release/*_ESP02*.bin.gz
